import { Action, Field, LogField, Relation, SettingField, Type } from '@/types/database'
import { Icon } from '@/types/icons'
import type { AppSchema } from '@/types/misc'
import {
  exampleChildColumns,
  exampleParentColumns,
  logColumns,
  settingColumns,
  testChildColumns,
  testParentColumns,
} from '@/services/blueprints/table-columns'

export const appSchema: AppSchema[] = [
  {
    type: Type.LOG,
    labelSingular: 'Log',
    labelPlural: 'Logs',
    icon: Icon.LOGS,
    supportedActions: [Action.INSPECT],
    visibleColumns: [LogField.TIMESTAMP, LogField.SEVERITY, LogField.LABEL],
    tableColumns: logColumns,
    fieldCards: [],
    chartCards: [],
  },
  {
    type: Type.SETTING,
    labelSingular: 'Setting',
    labelPlural: 'Settings',
    icon: Icon.SETTINGS,
    supportedActions: [],
    visibleColumns: [SettingField.KEY, SettingField.VALUE],
    tableColumns: settingColumns,
    fieldCards: [],
    chartCards: [],
  },
  {
    type: Type.EXAMPLE,
    relation: Relation.PARENT,
    labelSingular: 'Example Parent',
    labelPlural: 'Example Parents',
    icon: Icon.EXAMPLES,
    supportedActions: [Action.INSPECT, Action.CREATE, Action.EDIT, Action.DELETE, Action.CHARTS],
    visibleColumns: [Field.ID, Field.TIMESTAMP, Field.NAME],
    tableColumns: exampleParentColumns,
    fieldCards: [],
    chartCards: [],
  },
  {
    type: Type.EXAMPLE,
    relation: Relation.CHILD,
    labelSingular: 'Example Child',
    labelPlural: 'Example Children',
    icon: Icon.EXAMPLES,
    supportedActions: [Action.INSPECT, Action.CREATE, Action.EDIT, Action.DELETE],
    visibleColumns: [Field.ID, Field.TIMESTAMP],
    tableColumns: exampleChildColumns,
    fieldCards: [],
    chartCards: [],
  },
  {
    type: Type.TEST,
    relation: Relation.PARENT,
    labelSingular: 'Test Parent',
    labelPlural: 'Test Parents',
    icon: Icon.TESTS,
    supportedActions: [Action.INSPECT, Action.CREATE, Action.EDIT, Action.DELETE, Action.CHARTS],
    visibleColumns: [Field.ID, Field.TIMESTAMP, Field.NAME],
    tableColumns: testParentColumns,
    fieldCards: [],
    chartCards: [],
  },
  {
    type: Type.TEST,
    relation: Relation.CHILD,
    labelSingular: 'Test Child',
    labelPlural: 'Test Children',
    icon: Icon.TESTS,
    supportedActions: [Action.INSPECT, Action.CREATE, Action.EDIT, Action.DELETE],
    visibleColumns: [Field.ID, Field.TIMESTAMP],
    tableColumns: testChildColumns,
    fieldCards: [],
    chartCards: [],
  },
]
