import { Action, Field, Group, Type } from '@/types/database'
import type { DataSchema } from '@/types/misc'
import {
  exampleChildColumns,
  exampleParentColumns,
  logColumns,
  settingColumns,
  testChildColumns,
  testParentColumns,
} from '@/services/blueprints/table-columns'
import {
  exampleChildFields,
  exampleParentFields,
  logFields,
  settingFields,
  testChildFields,
  testParentFields,
} from '@/services/blueprints/field-props'
import {
  exampleChildValidator,
  exampleParentValidator,
  logValidator,
  settingValidator,
  testChildValidator,
  testParentValidator,
} from '@/services/validators'
import { Icon } from '@/types/icons'

export const dataSchema: DataSchema[] = [
  {
    type: Type.LOG,
    group: Group.INTERNAL,
    icon: Icon.LOGS,
    labelSingular: 'Log',
    labelPlural: 'Logs',
    validator: logValidator,
    supportedActions: [],
    visibleColumns: [Field.TIMESTAMP, Field.SEVERITY, Field.LABEL],
    tableColumns: logColumns,
    fieldProps: logFields,
    chartProps: [],
  },
  {
    type: Type.SETTING,
    group: Group.INTERNAL,
    icon: Icon.SETTINGS,
    labelSingular: 'Setting',
    labelPlural: 'Settings',
    validator: settingValidator,
    supportedActions: [],
    visibleColumns: [Field.KEY, Field.VALUE],
    tableColumns: settingColumns,
    fieldProps: settingFields,
    chartProps: [],
  },
  {
    type: Type.EXAMPLE_PARENT,
    childType: Type.EXAMPLE_CHILD,
    group: Group.PARENT,
    icon: Icon.EXAMPLES,
    labelSingular: 'Example Parent',
    labelPlural: 'Example Parents',
    validator: exampleParentValidator,
    supportedActions: [Action.INSPECT, Action.CREATE, Action.EDIT, Action.DELETE, Action.CHARTS],
    visibleColumns: [Field.ID, Field.TIMESTAMP, Field.NAME],
    tableColumns: exampleParentColumns,
    fieldProps: exampleParentFields,
    chartProps: [],
  },
  {
    type: Type.EXAMPLE_CHILD,
    group: Group.CHILD,
    icon: Icon.EXAMPLES,
    labelSingular: 'Example Child',
    labelPlural: 'Example Children',
    validator: exampleChildValidator,
    supportedActions: [Action.INSPECT, Action.CREATE, Action.EDIT, Action.DELETE],
    visibleColumns: [Field.ID, Field.TIMESTAMP],
    tableColumns: exampleChildColumns,
    fieldProps: exampleChildFields,
    chartProps: [],
  },
  {
    type: Type.TEST_PARENT,
    childType: Type.TEST_CHILD,
    group: Group.PARENT,
    icon: Icon.TESTS,
    labelSingular: 'Test Parent',
    labelPlural: 'Test Parents',
    validator: testParentValidator,
    supportedActions: [Action.INSPECT, Action.CREATE, Action.EDIT, Action.DELETE, Action.CHARTS],
    visibleColumns: [Field.ID, Field.TIMESTAMP, Field.NAME],
    tableColumns: testParentColumns,
    fieldProps: testParentFields,
    chartProps: [],
  },
  {
    type: Type.TEST_CHILD,
    group: Group.CHILD,
    icon: Icon.TESTS,
    labelSingular: 'Test Child',
    labelPlural: 'Test Children',
    validator: testChildValidator,
    supportedActions: [Action.INSPECT, Action.CREATE, Action.EDIT, Action.DELETE],
    visibleColumns: [Field.ID, Field.TIMESTAMP],
    tableColumns: testChildColumns,
    fieldProps: testChildFields,
    chartProps: [],
  },
]
