export enum RouteName {
  DASHBOARD = 'Dashboard',
  DATA_LOGS = 'DataLogs',
  DATA_SETTINGS = 'DataSettings',
  DATA_PARENTS = 'DataParents',
  DATA_CHILDREN = 'DataChildren',
  CREATE_PARENT = 'CreateParent',
  CREATE_CHILD = 'CreateChild',
  EDIT_PARENT = 'EditParent',
  EDIT_CHILD = 'EditChild',
  INSPECT_LOG = 'InspectLog',
  INSPECT_PARENT = 'InspectParent',
  INSPECT_CHILD = 'InspectChild',
  CHARTS = 'Charts',
  SETTINGS = 'Settings',
  FAQ = 'FAQ',
  ABOUT = 'About',
  DONATE = 'Donate',
  NOT_FOUND = 'NotFound',
}
